import type { Metadata } from "next";
import Link from "next/link";
import { InquiryForm, PageFrame, PageHero, SiteImage } from "../site-components";

export const metadata: Metadata = { title: "Events at Rosebud", description: "Plan a wedding, corporate gathering, golf outing, or private celebration at Rosebud." };

const amenities = ["Up to 120 guests", "Tables and chairs", "Flexible layouts", "Covered patio", "Attached bar", "Basic AV", "On-site parking", "In-house catering"];

export default function EventsPage() {
  return <PageFrame>
    <PageHero eyebrow="Events at Rosebud" title="Your gathering starts with the right kind of space." body="From wedding weekends and company dinners to charity tournaments and family celebrations, Rosebud makes it easy to bring people together." image={{ src: "/rosebud-images/event.png", alt: "Guests dining outdoors at Rosebud under string lights at sunset", position: "center" }}>
      <div className="button-row"><Link className="button button-cream" href="#event-types">Explore event types</Link><Link className="button button-outline-light" href="#event-inquiry">Check availability</Link></div>
    </PageHero>
    <section className="content-section section-shell" id="event-types">
      <div className="section-heading wide-heading"><p className="eyebrow">Choose your event</p><h2>Different plans. One experienced team.</h2><p>Start with the event that feels closest to yours. Each inquiry collects the details our team needs to check availability and recommend the right next step.</p></div>
      <div className="event-type-grid">
        <article className="event-type-card"><SiteImage className="event-type-image" src="/rosebud-images/event.png" alt="An intimate wedding dinner under string lights at Rosebud" position="center" /><div className="event-type-copy"><p className="eyebrow">Weddings</p><h3>Celebrate the whole story.</h3><p>Ceremonies, receptions, rehearsal dinners, and showers with golf-course views and room for up to 120 guests.</p><Link className="text-link" href="/events/weddings">Explore weddings <span>→</span></Link></div></article>
        <article className="event-type-card"><SiteImage className="event-type-image" src="/rosebud-images/clubhouse-patio.png" alt="The Rosebud clubhouse patio prepared for a company gathering" position="center" /><div className="event-type-copy"><p className="eyebrow">Corporate events</p><h3>Make getting together worthwhile.</h3><p>Company dinners, client events, meetings, holiday parties, and awards nights with food, bar, and AV options.</p><Link className="text-link" href="/events/corporate">Explore corporate events <span>→</span></Link></div></article>
        <article className="event-type-card"><SiteImage className="event-type-image" src="/rosebud-images/corporate-outing-carts.png" alt="Golf carts lined up for a corporate golf outing at Rosebud" position="center" /><div className="event-type-copy"><p className="eyebrow">Golf outings</p><h3>From first tee to final toast.</h3><p>Charity tournaments, customer events, fundraisers, and team golf days for groups of 24 to 144 players.</p><Link className="text-link" href="/outings">Explore golf outings <span>→</span></Link></div></article>
        <article className="event-type-card"><SiteImage className="event-type-image" src="/rosebud-images/rose-room.png" alt="The Rose Room arranged for a private celebration" position="center" /><div className="event-type-copy"><p className="eyebrow">Private celebrations</p><h3>Milestones feel at home here.</h3><p>Showers, birthdays, anniversaries, memorial receptions, and family gatherings in a warm, flexible room.</p><Link className="text-link" href="#event-inquiry">Start an inquiry <span>→</span></Link></div></article>
      </div>
    </section>
    <section className="content-section section-shell" id="rose-room"><div className="split"><SiteImage className="landscape-placeholder" src="/rosebud-images/rose-room.png" alt="The Rose Room arranged for a private event" position="center" /><div className="section-copy"><p className="eyebrow">The Rose Room</p><h2>Special without feeling formal.</h2><p>The Rose Room has large windows, neutral interiors, a covered patio, an attached bar, basic audiovisual equipment, and flexible table arrangements.</p><p>It is equally comfortable for a shower, company dinner, memorial reception, rehearsal dinner, or small wedding.</p></div></div></section>
    <section className="content-section soft-section"><div className="section-shell"><div className="section-heading"><p className="eyebrow">Room to make it yours</p><h2>What’s included.</h2></div><div className="amenity-grid">{amenities.map(item => <div className="amenity" key={item}>{item}</div>)}</div></div></section>
    <section className="content-section section-shell"><div className="intro-grid"><div><p className="eyebrow">In-house catering</p><h2>Food people actually want to eat.</h2></div><div><p>Choose from brunch, lunch, buffet, plated-dinner, appetizer, and dessert options. Our team can accommodate common dietary needs with advance notice.</p><p>Bar options include hosted, cash, and limited-service packages. Outside alcohol is not permitted.</p></div></div></section>
    <section className="content-section soft-section" id="event-inquiry"><div className="section-shell form-layout"><div className="form-intro"><p className="eyebrow">Check availability</p><h2>Tell us what you’re planning.</h2><p>Choose an event type and share the basics. This structured inquiry is the starting point for availability, package recommendations, and a personalized follow-up.</p></div><InquiryForm type="event" /></div></section>
  </PageFrame>;
}
